name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: robinraju/release-downloader@v1
        with:
          repository: 'CE-Programming/toolchain'
          latest: true
          preRelease: true
          fileName: 'CEdev-Linux-nightly.tar.gz'
          tarBall: false
          zipBall: false
          extract: true


      - name: Add to Path
        run: export PATH=$GITHUB_WORKSPACE/CEdev/bin:$PATH

      - name: Build Project
        run: make

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: bin/